version: 2
updates:
  # Monitora le dipendenze npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  # Monitora e aggiorna automaticamente le GitHub Actions stesse
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
