shamefullyHoist: true

autoInstallPeers: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  puppeteer: true
  unrs-resolver: false
  vue-demi: true

minimumReleaseAgeExclude:
  - nuxt
  - nuxt-nightly
  - '@nuxt/*'
  - vue
  - '@vue/*'
